const recipes = [
  {
    id: "1",
    name: "Spicy Thai Noodles",
    description: "Aromatic rice noodles tossed with Thai spices, fresh vegetables, and a tangy sauce. Perfect for a quick and flavorful meal.",
    image: "https://images.unsplash.com/photo-1707546944460-dda9069b9c1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGFpJTIwbm9vZGxlcyUyMHJlc3RhdXJhbnQlMjBwbGF0ZXxlbnwxfHx8fDE3NzMwMzYzNDF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "25 min",
    cost: "8",
    servings: "2",
    difficulty: "Medium",
    category: "Asian",
    ingredients: [
      { name: "Rice noodles", amount: "200g" },
      { name: "Thai basil", amount: "1/2 cup" },
      { name: "Soy sauce", amount: "2 tbsp" },
      { name: "Lime juice", amount: "1 tbsp" },
      { name: "Bell peppers", amount: "1" },
      { name: "Garlic", amount: "2 cloves" },
    ],
    steps: [
      "Cook rice noodles according to package. Drain and set aside.",
      "Heat oil in a wok, add garlic and stir until fragrant.",
      "Add bell peppers and stir-fry for 2 minutes.",
      "Add noodles, soy sauce, and lime juice. Toss well.",
      "Add Thai basil and serve immediately.",
    ],
    nutritions: {
      calories: "420",
      protein: "12",
      carbs: "65",
      fat: "12",
    },
  },
  {
    id: "2",
    name: "Vegetable Curry Bowl",
    description: "Creamy coconut curry loaded with seasonal vegetables and aromatic spices. A comforting and nutritious one-bowl meal.",
    image: "https://images.unsplash.com/photo-1729824159986-376b49c6b7e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjdXJyeSUyMGRpc2glMjBmb29kJTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzczMDM2MzQxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "30 min",
    cost: "10",
    servings: "3",
    difficulty: "Easy",
    category: "Indian",
    ingredients: [
      { name: "Coconut milk", amount: "400ml" },
      { name: "Curry paste", amount: "2 tbsp" },
      { name: "Cauliflower", amount: "1 cup" },
      { name: "Chickpeas", amount: "1 can" },
      { name: "Spinach", amount: "2 cups" },
      { name: "Onion", amount: "1" },
      { name: "Rice", amount: "1.5 cups cooked" },
    ],
    steps: [
      "Sauté onion until golden. Add curry paste and cook 1 minute.",
      "Pour in coconut milk and bring to simmer.",
      "Add cauliflower and chickpeas. Cook 15 minutes.",
      "Stir in spinach until wilted. Season with salt.",
      "Serve over steamed rice.",
    ],
    nutritions: {
      calories: "380",
      protein: "14",
      carbs: "48",
      fat: "18",
    },
  },
  {
    id: "3",
    name: "Asian Rice Bowl",
    description: "A balanced bowl of fluffy rice topped with stir-fried vegetables, protein, and a savory sauce. Simple yet satisfying.",
    image: "https://images.unsplash.com/photo-1664717698774-84f62382613b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHJpY2UlMjBib3dsJTIwcmVjaXBlfGVufDF8fHx8MTc3MzAzNjM0MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "20 min",
    cost: "7",
    servings: "2",
    difficulty: "Easy",
    category: "Asian",
    ingredients: [
      { name: "Jasmine rice", amount: "1 cup" },
      { name: "Broccoli", amount: "1 cup" },
      { name: "Carrots", amount: "1" },
      { name: "Soy sauce", amount: "2 tbsp" },
      { name: "Sesame oil", amount: "1 tsp" },
      { name: "Green onions", amount: "2" },
      { name: "Egg", amount: "1" },
    ],
    steps: [
      "Cook rice according to package instructions.",
      "Stir-fry broccoli and carrots in sesame oil.",
      "Fry egg sunny-side up. Set aside.",
      "Assemble bowl: rice, vegetables, egg on top.",
      "Drizzle with soy sauce and garnish with green onions.",
    ],
    nutritions: {
      calories: "450",
      protein: "16",
      carbs: "62",
      fat: "14",
    },
  },
  {
    id: "4",
    name: "Stir-Fry Vegetables",
    description: "Quick and colorful mix of crisp vegetables in a light garlic-ginger sauce. Ideal for a healthy weeknight dinner.",
    image: "https://images.unsplash.com/photo-1761314025701-34795be5f737?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGlyJTIwZnJ5JTIwdmVnZXRhYmxlcyUyMGRpbm5lcnxlbnwxfHx8fDE3NzMwMzYzNDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "15 min",
    cost: "6",
    servings: "2",
    difficulty: "Easy",
    category: "Asian",
    ingredients: [
      { name: "Broccoli", amount: "1 cup" },
      { name: "Snap peas", amount: "1 cup" },
      { name: "Carrots", amount: "2" },
      { name: "Garlic", amount: "3 cloves" },
      { name: "Ginger", amount: "1 tbsp" },
      { name: "Soy sauce", amount: "1 tbsp" },
      { name: "Vegetable oil", amount: "2 tbsp" },
    ],
    steps: [
      "Cut vegetables into bite-sized pieces.",
      "Heat oil in a large pan over high heat.",
      "Add garlic and ginger, stir 30 seconds.",
      "Add vegetables and stir-fry 5-7 minutes until crisp-tender.",
      "Add soy sauce, toss, and serve.",
    ],
    nutritions: {
      calories: "180",
      protein: "6",
      carbs: "22",
      fat: "8",
    },
  },
  {
    id: "5",
    name: "Healthy Pasta",
    description: "Whole wheat pasta with a light tomato-basil sauce and roasted vegetables. A wholesome twist on classic Italian pasta.",
    image: "https://images.unsplash.com/photo-1676300184847-4ee4030409c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwcGFzdGElMjBkaXNoJTIwbWVhbHxlbnwxfHx8fDE3NzMwMzYzNDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "20 min",
    cost: "9",
    servings: "3",
    difficulty: "Easy",
    category: "Italian",
    ingredients: [
      { name: "Whole wheat pasta", amount: "300g" },
      { name: "Tomatoes", amount: "3" },
      { name: "Fresh basil", amount: "1/2 cup" },
      { name: "Zucchini", amount: "1" },
      { name: "Olive oil", amount: "2 tbsp" },
      { name: "Garlic", amount: "2 cloves" },
      { name: "Parmesan", amount: "1/4 cup" },
    ],
    steps: [
      "Cook pasta al dente. Reserve 1/2 cup pasta water.",
      "Sauté garlic in olive oil. Add diced tomatoes and simmer 10 min.",
      "Add zucchini and cook 3 minutes.",
      "Toss pasta with sauce, basil, and pasta water.",
      "Top with Parmesan and serve.",
    ],
    nutritions: {
      calories: "380",
      protein: "14",
      carbs: "58",
      fat: "10",
    },
  },
  {
    id: "6",
    name: "Delicious Food Bowl",
    description: "A vibrant grain bowl with quinoa, roasted vegetables, avocado, and a creamy tahini dressing. Packed with flavor and nutrients.",
    image: "https://images.unsplash.com/photo-1707897687558-22bdecb2e1c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZWxpY2lvdXMlMjBhc2lhbiUyMGZvb2QlMjBib3dsfGVufDF8fHx8MTc3MzAzNjMzOXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "25 min",
    cost: "11",
    servings: "2",
    difficulty: "Medium",
    category: "Asian",
    ingredients: [
      { name: "Quinoa", amount: "1 cup" },
      { name: "Sweet potato", amount: "1" },
      { name: "Avocado", amount: "1" },
      { name: "Tahini", amount: "2 tbsp" },
      { name: "Lemon juice", amount: "1 tbsp" },
      { name: "Chickpeas", amount: "1/2 can" },
      { name: "Kale", amount: "2 cups" },
    ],
    steps: [
      "Cook quinoa. Roast sweet potato cubes at 400°F for 20 min.",
      "Whisk tahini with lemon juice and water for dressing.",
      "Massage kale with a pinch of salt.",
      "Assemble: quinoa, kale, roasted sweet potato, chickpeas, avocado.",
      "Drizzle with tahini dressing.",
    ],
    nutritions: {
      calories: "520",
      protein: "18",
      carbs: "62",
      fat: "24",
    },
  },
  {
    id: "7",
    name: "Quick Ramen",
    description: "Upgraded instant ramen with a soft-boiled egg, nori, and green onions. Comfort food ready in minutes.",
    image: "https://images.unsplash.com/photo-1673824085288-ea05299e4f72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHN0dWRlbnQlMjBjb29raW5nJTIwcmFtZW4lMjBub29kbGVzfGVufDF8fHx8MTc3MzAzNjMzOHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "10 min",
    cost: "5",
    servings: "1",
    difficulty: "Easy",
    category: "Asian",
    ingredients: [
      { name: "Ramen noodles", amount: "1 pack" },
      { name: "Egg", amount: "1" },
      { name: "Green onions", amount: "2" },
      { name: "Nori sheet", amount: "1" },
      { name: "Sesame seeds", amount: "1 tsp" },
      { name: "Soy sauce", amount: "1 tbsp" },
    ],
    steps: [
      "Boil water. Cook ramen according to package.",
      "Soft-boil egg: 6 min in boiling water, then cool.",
      "Slice green onions. Cut nori into strips.",
      "Place noodles in bowl, add broth. Top with egg, nori, green onions.",
      "Drizzle soy sauce and sprinkle sesame seeds.",
    ],
    nutritions: {
      calories: "420",
      protein: "16",
      carbs: "52",
      fat: "16",
    },
  },
  {
    id: "8",
    name: "Fresh Ingredients Mix",
    description: "A colorful medley of roasted and raw vegetables with herbs and a light vinaigrette. Perfect for a refreshing side or light meal.",
    image: "https://images.unsplash.com/photo-1757332914538-4b5ed7ae95e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xvcmZ1bCUyMGZvb2QlMjBpbmdyZWRpZW50cyUyMHZlZ2V0YWJsZXMlMjBjb29raW5nfGVufDF8fHx8MTc3MzAzNjMzOXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    time: "35 min",
    cost: "12",
    servings: "4",
    difficulty: "Medium",
    category: "Healthy",
    ingredients: [
      { name: "Bell peppers", amount: "3" },
      { name: "Eggplant", amount: "1" },
      { name: "Cherry tomatoes", amount: "2 cups" },
      { name: "Cucumber", amount: "1" },
      { name: "Fresh herbs", amount: "1/4 cup" },
      { name: "Olive oil", amount: "3 tbsp" },
      { name: "Balsamic vinegar", amount: "1 tbsp" },
    ],
    steps: [
      "Chop peppers and eggplant. Toss with oil, roast 25 min at 400°F.",
      "Halve cherry tomatoes. Dice cucumber.",
      "Combine roasted vegetables with tomatoes and cucumber.",
      "Whisk olive oil and balsamic for vinaigrette.",
      "Drizzle over vegetables, add herbs, and serve.",
    ],
    nutritions: {
      calories: "140",
      protein: "4",
      carbs: "18",
      fat: "7",
    },
  },
];

export { recipes };
